# Base Docker Compose file for MCP Prompts
# This file provides the foundational configuration


name: mcp-prompts

services:
  # MCP Prompts Server with File Storage (default)
  mcp-prompts:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: sparesparrow/mcp-prompts:latest
    container_name: mcp-prompts
    environment:
      - NODE_ENV=production
      - STORAGE_TYPE=file
      - PROMPTS_DIR=/app/data/prompts
      - BACKUPS_DIR=/app/data/backups
      - LOG_LEVEL=info
      - HTTP_SERVER=true
      - PORT=3003
      - HOST=0.0.0.0
    volumes:
      - mcp-data:/app/data
    ports:
      - "3003:3003"
    healthcheck:
      test: ["CMD-SHELL", "/health-check.sh"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
    networks:
      - mcp-network

volumes:
  mcp-data:
    name: mcp-prompts-data

networks:
  mcp-network:
    driver: bridge
