blank_issues_enabled: false
contact_links:
  - name: General Questions & Community Support
    url: https://github.com/sparesparrow/mcp-prompts/discussions
    about: Please ask and answer questions here. 