name: Feature request
description: Suggest an idea or request a new feature
labels: [type: enhancement, needs triage]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: A clear and concise description of the feature or enhancement.
      placeholder: "I would like to ..."
  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Use case
      description: Why is this feature important? What problem does it solve?
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you imagine this feature working? Any ideas for implementation?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context, links, or screenshots about the feature request here. 