name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (ESLint)
        run: npm run lint

      - name: Check formatting (Prettier)
        run: npm run format:check

      - name: Run unit & integration tests
        run: npm test

      - name: Validate prompts
        run: npm run validate:prompts

      - name: Build
        run: npm run build --if-present

      - name: Audit dependencies
        run: npm audit --audit-level=moderate

      - name: Run coverage
        run: npm run test:coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/

      - name: Upload coverage to Codecov
        if: env.CODECOV_TOKEN != null
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

      - name: Run E2E health check
        run: |
          # Start server in the background
          node dist/scripts/start-server.js --port 3003 &
          # Wait for the server to initialize
          sleep 10
          # Check the health endpoint
          echo "Pinging health check endpoint..."
          curl --fail http://localhost:3003/health
          # Check the version command
          echo "Checking CLI version..."
          node dist/index.js --version

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mcp_prompts_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: npm run test:unit
      
      - name: Run integration tests
        run: npm run test:integration
        env:
          PG_HOST: localhost
          PG_PORT: 5432
          PG_DATABASE: mcp_prompts_test
          PG_USER: postgres
          PG_PASSWORD: postgres
          PG_SSL: false
      
      - name: Run build test
        run: npm run test:build
      
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/

  docker-tests:
    name: Docker Tests
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Run Docker tests
        run: npm run test:docker
      
      - name: Upload Docker test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: docker-test-results
          path: test-results/

  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    needs: [test, docker-tests]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build package
        run: npm run build
      
      - name: Determine version bump
        id: bump
        run: |
          LATEST_COMMIT=$(git log -1 --pretty=format:%s)
          if [[ "$LATEST_COMMIT" == *"BREAKING CHANGE"* || "$LATEST_COMMIT" == *"!:"* ]]; then
            echo "VERSION_TYPE=major" >> $GITHUB_OUTPUT
          elif [[ "$LATEST_COMMIT" == *"feat:"* ]]; then
            echo "VERSION_TYPE=minor" >> $GITHUB_OUTPUT
          else
            echo "VERSION_TYPE=patch" >> $GITHUB_OUTPUT
          fi
      
      - name: Publish to npm
        run: npx --no-install ./scripts/release.sh --version ${{ steps.bump.outputs.VERSION_TYPE }} --publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            sparesparrow/mcp-prompts:latest
            sparesparrow/mcp-prompts:${{ steps.bump.outputs.VERSION_TYPE }}
